version: "3"

networks:
    monitoring:
        driver: bridge

services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - grafana:/var/lib/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SERVER_ROOT_URL=http://grafana.danielof.com/
        restart: unless-stopped
        networks:
            - monitoring

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - prometheus:/prometheus
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/prometheus/http_targets.json:/etc/prometheus/http_targets.json
            - ./config/prometheus/icmp_targets.json:/etc/prometheus/icmp_targets.json
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.external-url=http://prometheus.danielof.com/
        restart: unless-stopped
        networks:
            - monitoring

    blackbox-exporter:
        container_name: blackbox
        image: danielofir/blackbox-exporter
        ports:
            - "9115:9115"
        volumes:
            - blackbox_exporter:/blackbox-exporter
            - ./config/blackbox-exporter:/config
        command:
            - --config.file=/config/blackbox.yml
        restart: unless-stopped
        networks:
            - monitoring

    nginx-reverse-proxy:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/grafana/ssl/:/etc/ssl/grafana/private/
            - ./config/nginx/prometheus/ssl/:/etc/ssl/prometheus/private/
            - ./config/nginx/grafana/includes/:/etc/nginx/grafana/includes/
            - ./config/nginx/prometheus/includes/:/etc/nginx/prometheus/includes/
        restart: unless-stopped
        networks:
            - monitoring
    
    nginx_exporter:
        container_name: nginx_exporter
        image: nginx/nginx-prometheus-exporter
        ports:
            - "9113:9113"
        command:
            - -nginx.scrape-uri
            - http://192.168.1.213/stub_status
        networks:
            - monitoring

volumes:
    grafana:
    prometheus:
    blackbox_exporter:
