global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
      monitor: 'DanielO'
scrape_configs:

- job_name: 'blackbox-http'
  metrics_path: /probe
  params:
    module: [http_2xx]
  file_sd_configs:
          - files:
                  - 'http_targets.json'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    #replacement: 192.168.1.213:9115
    replacement: blackbox:9115 

- job_name: 'blackbox-icmp'
  metrics_path: /probe
  params:
    module: [icmp]
  file_sd_configs:
  - files:
    - 'icmp_targets.json'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    #replacement: 192.168.1.213:9115 
    replacement: blackbox-exporter:9115

- job_name: node_exporter
  static_configs:
          - targets: ['192.168.1.213:9100','192.168.1.131:9100','10.6.0.2:9100']

- job_name: pihole_exporter
  static_configs:
          - targets: ['192.168.1.213:9617']
 
